<h2>Policy för personlig integritet</h2>
<div>
    <h3>Introduktion</h3>
    <p>Community-ID.org respekterar varje individs rätt till personlig integritet. Vi samlar och använder därför bara den information som anges i denna policy. Policyn gäller all information på Community-ID.org's webbplats.</p>

    <h3>Informationsinsamling</h3>
    <p>Community-ID.org samlar information via webbplatsen för att kunna ge användarna en effektiv upplevelse. Vi samlar personlig information, inklusive e-postadresser, från registrerade användare. Vi samlar även in IP-addresser och hur besökarna använder vår webbplats, för att kunna felsöka och förbättra vårt system och våra tjänster. We may also collect ancillary usage information, including referrals, access times and platform type, which our users divulge through visiting the site.</p>

    <h3>Cookies</h3>
    <p>Community-ID.org använder cookies. En cookie är en liten textfile som vår webbserver lägger i användarens dator för unik identifiering. Cookies gör det möjligt för Community-ID.org att spåra användningsmönster och leverera anpassat innehåll till användaren. Våra cookies har ett bäst-före-datum och används inte för att samla personrelaterad information.</p>
    <p>Vill du inte acceptera cookies kan din webbläsare ställas in så att du automatiskt nekar till lagring av cookies eller informeras varje gång en webbplats begär att få lagra en cookie. Genom webbläsaren kan också tidigare lagrade cookies raderas. Se webbläsarens hjälpsidor för mer information.</p>

    <h3>Informationsanvändning</h3>
    <p>Vi kommer inte att hyra ut eller sälja din personliga information till tredje part. Vi kommer endast att dela med oss av personlig information i följande fall: 1) Affärstransaktioner: Om Community-ID.org blir uppköpt kommer den personliga informationen följa med om det framgår i kontraktet. 2) Lagkrav: Om det enligt lag krävs att information ska lämnas ut, så kommer Community-ID.org att göra det.</p>

    <h3>Informationsförvaring och - Kontroll</h3>
    <p>När en användare raderar sitt konto från Community-ID.org, kommer all deras information raderas fullständigt. Naturligtvis kan det finnas kvar äldre säkerhetskopior av informationen, men dessa raderas regelbundet. Vi anser att du ska kontrollera din egen information och respekterar det fullt ut.</p>
</div>
