<form name="installform" method="post" action="<?php echo $this->base ?>/install/credentials/save" class="formGrid">
    <h3>
        <?php echo $this->translate('Database and E-mail information') ?>
    </h3>
    <div class="yui-gf" style="margin-top:20px">
        <?php echo $this->form->hostname ?>
        <?php echo $this->form->dbname ?>
        <?php echo $this->form->dbusername ?>
        <?php echo $this->form->dbpassword ?>
        <?php echo $this->form->supportemail ?>
    </div>
    <h3>
        <?php echo $this->translate('Administrator User Information') ?>
    </h3>
    <div class="yui-gf" style="margin-top:20px">
        <?php echo $this->form->username ?>
        <?php echo $this->form->password1 ?>
        <?php echo $this->form->password2 ?>
    </div>
    <input type="submit" id="send" value="<?php echo $this->translate('Send') ?>" />
    <script type="text/javascript">
        var oButton = new YAHOO.widget.Button("send");
    </script> 
</form>
