<?php echo $this->translate('Please enter your E-mail below to receive a link to reset your password') ?>
<form method="post" action="<?php echo $this->base ?>/users/recoverpassword/send">
    <?php echo $this->form->email ?>
    <input type="submit" id="send" value="<?php echo $this->translate('Send') ?>" />
    <script type="text/javascript">
        var oButton = new YAHOO.widget.Button("send");
    </script> 
</form>
