<p>
    Community-ID es un servicio traído a ustedes por Keyboard Monkeys Ltd., Community as a Service &#x2122;.
</p>

<p>
    Keyboard Monkeys Ltd. está enfocada en proveer productos y soluciones Open Source dirijidas a la potenciación de comunidades a través de Internet. También hacemos consultoría privada, proporcionando un amplio rango de soporte a tecnologías Open Source, pero especialmente ofreciendo productos y soluciones basados en comunidades.
</p>

<p>
    Estos son otros productos y servicio actualmente ofrecidos, o en desarrollo:
    <ul>
        <li>
            <b><a href="http://sourceforge.net/projects/sciret">Sciret</a></b> - Sistema Empresarial de Base de Conocimientos
        </li>
        <li>
            <b><a href="http://sourceforge.net/projects/textroller">TextRoller</a></b> - Plataforma de Blogging
        </li>
        <li>
            <b>Community Solutions</b> - Open Source Project Collaboration (actualmente bajo desarrollo)
        </li>
    </ul>
</p>
