<p>
    Community-ID ist ein Service, zur Verfügung gestellt mit freundlicher Unterstützung von Keyboard Monkeys Ltd., Community as a Service &#x2122;.
</p>

<p>
    Keyboard Monkeys Ltd. konzentriert sich auf Open-Source-Lösungen und Produkte zur Bildung von Communities über das Internet. Wie bieten auch Consulting so wie ein breites Spektrum an Unterstützung für Open-Source-Technologien aber speziell bieten wir Community-basierte Lösungen und Produkte. 
</p>

<p>
 Weitere Produkte oder Services welche wir zur Zeit anbieten oder welche sich in der Planung befinden: 
    <ul>
        <li>
            <b><a href="http://sourceforge.net/projects/sciret">Sciret</a></b> - Enterprise Knowledge Base System
        </li>
        <li>
            <b><a href="http://sourceforge.net/projects/textroller">TextRoller</a></b> - Blogging Platform
        </li>
        <li>
            <b>Community Solutions</b> - Open Source Project Collaboration (Zur Zeit unter interner Entwicklung)
        </li>
    </ul>
</p>
