<p>
    Community-ID is a service brought to you by Keyboard Monkeys Ltd., Community as a Service &#x2122;.
</p>

<p>
    Keyboard Monkeys Ltd. focuses on providing open source solutions and products aimed at empowering communities accross the Internet. We also do private consulting, providing a wide range of support for open source technologies, but specially we are offering community based solutions and products.
</p>

<p>
    These are other services and products currently offered, or under planning:
    <ul>
        <li>
            <b><a href="http://sourceforge.net/projects/sciret">Sciret</a></b> - Enterprise Knowledge Base System
        </li>
        <li>
            <b><a href="http://sourceforge.net/projects/textroller">TextRoller</a></b> - Blogging platform
        </li>
        <li>
            <b>Community Solutions</b> - Open Source Project Collaboration (Currently under initial development stages)
        </li>
    </ul>
</p>
