<p>
    Community-IDは、Keyboard Monkeys Ltd., Community as a Service &#x2122;によって提供されるサービスです。
</p>

<p>
    Keyboard Monkeys Ltd. は、インターネットのコミュニティに対して貢献できるオープンソースのソリューションや製品を提供することに力を注いでおります。 私どもは個別のコンサルティングに加え幅広いオープンソース技術に関するサポートを行っております。なかでもコミュニティを基本としたソリューションや製品を得意としています。
</p>

<p>
    その他のサービスや製品（計画中を含みます）には以下の様なものがあります:

    <ul>
        <li>
            <b><a href="http://sourceforge.net/projects/sciret">Sciret</a></b> - Enterprise Knowledge Base System
        </li>
        <li>
            <b><a href="http://sourceforge.net/projects/textroller">TextRoller</a></b> - Blogging platform
        </li>
        <li>
            <b>Community Solutions</b> - Open Source Project Collaboration (Currently under initial development stages)
        </li>
    </ul>
</p>
