<p>
    Community-ID è un servizio fornito da Keyboard Monkeys Ltd., Community as a Service &#x2122;.
</p>

<p>
    Keyboard Monkeys Ltd. si concentra sul fornire soluzioni open source e prodotti mirati a rendere più forti le community su Internet. Forniamo inoltre consulenza, con un ampio supporto per le tecnologie open source, sopratutto soluzioni e prodotti per le community.
</p>

<p>
    Questi sono i nostri prodotti e servizi attualmente forniti o in corso di sviluppo:
    <ul>
        <li>
            <b><a href="http://sourceforge.net/projects/sciret">Sciret</a></b> - Enterprise Knowledge Base System
        </li>
        <li>
            <b><a href="http://sourceforge.net/projects/textroller">TextRoller</a></b> - Piattaforma per blog
        </li>
        <li>
            <b>Community Solutions</b> - Open Source Project Collaboration (Attualmente in sviluppo)
        </li>
    </ul>
</p>
