<p>
    Community-ID är en tjänst som levereras till dig av Keyboard Monkeys Ltd., Community as a Service &#x2122;.
</p>

<p>
    Keyboard Monkeys Ltd. fokuserar på att erbjuda öppen källkodslösningar och -produkter för att stärka nätverkandet på Internet. Vi erbjuder även konsulttjänster för en stor mängd öppen källkodstekniker, speciellt då lösningar och produkter för nätverkande.
</p>

<p>
    Följande tjänster och produkter finns tillgängliga eller under utveckling:
    <ul>
        <li>
            <b><a href="http://sourceforge.net/projects/sciret">Sciret</a></b> - Avancerad kunskapsdatabas/expertsystem
        </li>
        <li>
            <b><a href="http://sourceforge.net/projects/textroller">TextRoller</a></b> - Blog-plattform
        </li>
        <li>
            <b>Community Solutions</b> - Samarbetsplattform för öppen källkods-utveckling (under utveckling)
        </li>
    </ul>
</p>
