<form name="changePasswordForm" class="formGrid" >
    <?php echo $this->changePasswordForm->password1 ?>
    <?php echo $this->changePasswordForm->password2 ?>
    <div class="yui-gf">
        <div class="yui-u first">&nbsp;</div>
        <div class="yui-u">
            <input type="button" id="save" value="<?php echo $this->translate('Save') ?>" onclick="COMMID.changePassword.save()" />
            <input type="button" id="cancel" value="<?php echo $this->translate('Cancel') ?>" onclick="COMMID.changePassword.cancel()" />
            <script type="text/javascript">
                var oButton = new YAHOO.widget.Button(
                    "save",
                    {
                        type    : "push",
                        onclick : {fn: function() {COMMID.changePassword.save(<?php echo $this->targetUser->id ?>)}}
                    }
                );
                var oButton = new YAHOO.widget.Button(
                    "cancel",
                    {
                        type    : "push",
                        onclick : {fn: function() {COMMID.changePassword.cancel(<?php echo $this->targetUser->id ?>)}}
                    }
                );
            </script> 
        </div>
    </div>
</form>
