<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Error</title>
</head>
<body>
    <h2>An error occurred</h2>
    <strong><?php echo $this->message ?></strong>
    <?php if ($this->trace): ?>
    <pre>
Stack Trace:
<?php echo $this->trace ?>
    </pre>
    <?php endif ?>
</body>
</html>

